---
inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Max: 120

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Naming/MethodParameterName:
  AllowedNames: [x, y, z]

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'

Style/SymbolArray:
  Enabled: true

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - vendor/bundle/**/*
  NewCops: enable
  TargetRubyVersion: 2.6
