Metrics/ClassLength:
  Max: 300

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/DoubleNegation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'

Style/PredicateName:
  Exclude:
    # Bindata has problems with srid? since srid is a parsed attribute. #z? and
    # m? could get around this but it seemed more important to keep the API
    # consistent.
    - lib/ogr/geometry_extensions/ewkb_record.rb
    - lib/ogr/geometry_extensions/wkb_record.rb

Style/SymbolArray:
  Enabled: true

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - Gemfile
  Exclude:
    - vendor/bundle/**/*
  TargetRubyVersion: 2.2
