Metrics/ClassLength:
  Max: 300

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/DoubleNegation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'

Style/SymbolArray:
  Enabled: true

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - Gemfile
  Exclude:
    - vendor/bundle/**/*
  TargetRubyVersion: 2.2
